---
name: mycicd

on:
  push:
    branches:
      - master

jobs: 
  pullcicd:
    runs-on: ubuntu-latest
    steps:
      - name: workflow started
        run: echo "Workflow started"

      - name: checkout
        uses: actions/checkout@v2

      - name: Building docker image
        run: docker build -t flaskrun . 
       
      - name: ls docker image
        run: docker images
     
      - name: login into dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}} 
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      - name: docker push
        run: docker tag flaskrun:latest flaskrun:2
             docker push shilpakhurana/flask-repo:2

      - name: ssh into server
        run: | 
          echo "This step will always run"
        
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          cat SSH_KEY > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName "43.205.255.238"
            User cicd
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
      
      - name: Running 
        run: ssh staging 'echo $USER'

      - name: Running gitpull
        run: ssh staging 'bash /var/www/cicd.sh'

      - name: workflow completed
        run: echo "check server output" 

